"""initial schema

Revision ID: 2ff7a65e98ad
Revises: 
Create Date: 2025-11-21 20:56:50.253274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ff7a65e98ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_metadata',
    sa.Column('movie_id', sa.Text(), nullable=False),
    sa.Column('movie_name', sa.Text(), nullable=False),
    sa.Column('genres', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('release_date', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('actors', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('director', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('poster_path', sa.Text(), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index('idx_movie_metadata_genres', 'movie_metadata', ['genres'], unique=False, postgresql_using='gin')
    op.create_table('user_login',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('movie_embedding_coldstart',
    sa.Column('movie_id', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index('idx_movie_embedding_coldstart_hnsw', 'movie_embedding_coldstart', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('movie_embedding_personalized',
    sa.Column('movie_id', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index('idx_movie_embedding_personalized_hnsw', 'movie_embedding_personalized', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('movie_rating_stats',
    sa.Column('movie_id', sa.Text(), nullable=False),
    sa.Column('avg_rating', sa.REAL(), server_default='0.0', nullable=True),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('rating_count_log', sa.REAL(), server_default='0.0', nullable=True),
    sa.Column('tmdb_avg_rating', sa.REAL(), server_default='0.0', nullable=True),
    sa.Column('tmdb_vote_log', sa.REAL(), server_default='0.0', nullable=True),
    sa.Column('tmdb_popularity', sa.REAL(), server_default='0.0', nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('user_embeddings',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_login.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_user_embeddings_hnsw', 'user_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('user_genre_embeddings',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('genre_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_login.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_rating_stats',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('avg_rating', sa.REAL(), server_default='0.0', nullable=True),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('rating_count_log', sa.REAL(), server_default='0.0', nullable=True),
    sa.Column('top_3_genres', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('top_50_actors', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('top_10_directors', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_login.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_watchlist',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('movie_id', sa.Text(), nullable=False),
    sa.Column('user_rating', sa.REAL(), server_default='0.0', nullable=True),
    sa.Column('added_at', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_login.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_watchlist')
    op.drop_table('user_rating_stats')
    op.drop_table('user_genre_embeddings')
    op.drop_index('idx_user_embeddings_hnsw', table_name='user_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('user_embeddings')
    op.drop_table('movie_rating_stats')
    op.drop_index('idx_movie_embedding_personalized_hnsw', table_name='movie_embedding_personalized', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('movie_embedding_personalized')
    op.drop_index('idx_movie_embedding_coldstart_hnsw', table_name='movie_embedding_coldstart', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('movie_embedding_coldstart')
    op.drop_table('user_login')
    op.drop_index('idx_movie_metadata_genres', table_name='movie_metadata', postgresql_using='gin')
    op.drop_table('movie_metadata')
    # ### end Alembic commands ###
