export const dummyData = [
    {id: "1", name: "movie 1", desc: "movie description", genres: ["Adventure", "Sci-Fi", "Comedy"], release_date: 2017, actors: ["actor 1", "actor 2"], director: ["director 1", "director 2"], rating: 0, poster_path: "idk.com"},
    {id: "2", name: "movie 2", desc: "movie description", genres: ["Mystery", "Adventure", "Action"], release_date: 2018, actors: ["actor 1", "actor 2"], director: ["director 1", "director 2"], rating: 0, poster_path: "idk.com"},
    {id: "3", name: "movie 3", desc: "movie description", genres: ["Sci-Fi", "Comedy", "Mystery"], release_date: 2024, actors: ["actor 1", "actor 2"], director: ["director 1", "director 2"], rating: 0, poster_path: "idk.com"},
    {id: "4", name: "movie 4", desc: "movie description", genres: ["Mystery", "Action", "Sci-Fi"], release_date: 2000, actors: ["actor 1", "actor 2"], director: ["director 1", "director 2"], rating: 0, poster_path: "idk.com"},
    {id: "5", name: "movie 5", desc: "movie description", genres: ["Adventure", "Comedy", "Mystery"], release_date: 1997, actors: ["actor 1", "actor 2"], director: ["director 1", "director 2"], rating: 0, poster_path: "idk.com"},
    {id: "6", name: "movie 6", desc: "movie description", genres: ["Action", "Mystery", "Horror"], release_date: 2015, actors: ["actor 1", "actor 2"], director: ["director 1", "director 2"], rating: 0, poster_path: "idk.com"},
    {id: "7", name: "movie 7", desc: "movie description", genres: ["Action", "Adventure", "Horror"], release_date: 2014, actors: ["actor 1", "actor 2"], director: ["director 1", "director 2"], rating: 0, poster_path: "idk.com"},
    {id: "8", name: "movie 8", desc: "movie description", genres: ["Comedy", "Sci-Fi", "Action"], release_date: 2011, actors: ["actor 1", "actor 2"], director: ["director 1", "director 2"], rating: 0, poster_path: "idk.com"},
    {id: "9", name: "movie 9", desc: "movie description", genres: ["Adventure", "Mystery", "Sci-Fi"], release_date: 2017, actors: ["actor 1", "actor 2"], director: ["director 1", "director 2"], rating: 0, poster_path: "idk.com"},
]