"""added language column to movie metadata table

Revision ID: 368274c15ee4
Revises: c3ba5146a755
Create Date: 2025-12-01 22:59:08.128634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '368274c15ee4'
down_revision: Union[str, Sequence[str], None] = 'c3ba5146a755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_metadata', sa.Column('language', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_metadata', 'language')
    # ### end Alembic commands ###
