"""Created Prod and Staging tables for movie embeddings for rollback

Revision ID: 4e65a18fb0c9
Revises: 9d9cee5b2677
Create Date: 2025-11-30 16:36:02.302564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '4e65a18fb0c9'
down_revision: Union[str, Sequence[str], None] = '9d9cee5b2677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_embedding_coldstart_prod',
    sa.Column('movie_id', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index('idx_movie_embedding_coldstart_prod_hnsw', 'movie_embedding_coldstart_prod', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('movie_embedding_coldstart_staging',
    sa.Column('movie_id', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index('idx_movie_embedding_coldstart_staging_hnsw', 'movie_embedding_coldstart_staging', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('movie_embedding_personalized_prod',
    sa.Column('movie_id', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index('idx_movie_embedding_personalized_prod_hnsw', 'movie_embedding_personalized_prod', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('movie_embedding_personalized_staging',
    sa.Column('movie_id', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index('idx_movie_embedding_personalized_staging_hnsw', 'movie_embedding_personalized_staging', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('idx_movie_embedding_coldstart_hnsw'), table_name='movie_embedding_coldstart', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_table('movie_embedding_coldstart')
    op.drop_index(op.f('idx_movie_embedding_personalized_hnsw'), table_name='movie_embedding_personalized', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_table('movie_embedding_personalized')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_embedding_personalized',
    sa.Column('movie_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], name=op.f('movie_embedding_personalized_movie_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', name=op.f('movie_embedding_personalized_pkey'))
    )
    op.create_index(op.f('idx_movie_embedding_personalized_hnsw'), 'movie_embedding_personalized', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('movie_embedding_coldstart',
    sa.Column('movie_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], name=op.f('movie_embedding_coldstart_movie_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', name=op.f('movie_embedding_coldstart_pkey'))
    )
    op.create_index(op.f('idx_movie_embedding_coldstart_hnsw'), 'movie_embedding_coldstart', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('idx_movie_embedding_personalized_staging_hnsw', table_name='movie_embedding_personalized_staging', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('movie_embedding_personalized_staging')
    op.drop_index('idx_movie_embedding_personalized_prod_hnsw', table_name='movie_embedding_personalized_prod', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('movie_embedding_personalized_prod')
    op.drop_index('idx_movie_embedding_coldstart_staging_hnsw', table_name='movie_embedding_coldstart_staging', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('movie_embedding_coldstart_staging')
    op.drop_index('idx_movie_embedding_coldstart_prod_hnsw', table_name='movie_embedding_coldstart_prod', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('movie_embedding_coldstart_prod')
    # ### end Alembic commands ###
