"""added is_stale column to userRatingStats to optimize deleting movie from watchlist and rating movies queries

Revision ID: 70625248663f
Revises: 4e65a18fb0c9
Create Date: 2025-12-01 03:15:51.653901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '70625248663f'
down_revision: Union[str, Sequence[str], None] = '4e65a18fb0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_rating_stats', sa.Column('is_stale', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_rating_stats', 'is_stale')
    # ### end Alembic commands ###
