"""Added Sessions Table and removed unique constraint for username in UserLogin Table

Revision ID: 9d9cee5b2677
Revises: 2ff7a65e98ad
Create Date: 2025-11-26 03:24:45.443471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9d9cee5b2677'
down_revision: Union[str, Sequence[str], None] = '2ff7a65e98ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('session_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='NOW()', nullable=True),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_login.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=True)
    op.drop_constraint(op.f('user_login_username_key'), 'user_login', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_login_username_key'), 'user_login', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
