"""added user_not_seen_movie table to handle movies that the user marked as not seen before

Revision ID: 9ddace2ac252
Revises: 70625248663f
Create Date: 2025-12-01 04:38:38.626860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9ddace2ac252'
down_revision: Union[str, Sequence[str], None] = '70625248663f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_not_seen_movie',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('movie_id', sa.Text(), nullable=False),
    sa.Column('dismissed_at', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.Column('dismissed_until', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_metadata.movie_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_login.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_not_seen_movie')
    # ### end Alembic commands ###
