"""updated dismissed_at and dismissed_until columns in User_not_seen_movie table to be timezone aware instead of a regular timestamp

Revision ID: c3ba5146a755
Revises: 9ddace2ac252
Create Date: 2025-12-01 05:12:41.356433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3ba5146a755'
down_revision: Union[str, Sequence[str], None] = '9ddace2ac252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_not_seen_movie', 'dismissed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text("'2025-12-01 12:38:42.288853'::timestamp without time zone"))
    op.alter_column('user_not_seen_movie', 'dismissed_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_not_seen_movie', 'dismissed_until',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_not_seen_movie', 'dismissed_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text("'2025-12-01 12:38:42.288853'::timestamp without time zone"))
    # ### end Alembic commands ###
